GET http://127.0.0.1:10001/movies/
Accept: application/json

###

GET http://127.0.0.1:10001/movies/?director_id=12
Accept: application/json

###

GET http://127.0.0.1:10001/movies/?genre_id=4
Accept: application/json

###

GET http://127.0.0.1:10001/movies/?year=2010
Accept: application/json

###

GET http://127.0.0.1:10001/directors/
Accept: application/json

###

GET http://127.0.0.1:10001/directors/1
Accept: application/json

###

GET http://127.0.0.1:10001/genres/
Accept: application/json

###

GET http://127.0.0.1:10001/genres/1
Accept: application/json

###

GET http://127.0.0.1:10001/movies/21
Accept: application/json

###

POST http://127.0.0.1:10001/movies/
Accept: application/json
Content-Type: application/json

{
  "title": "Гарри Поттер мой кумир!",
  "trailer": "таким фильмам не нужны трейлеры",
  "year": 1990,
  "rating": 10,
  "description": "10 из 10!"
}

###

PUT http://127.0.0.1:10001/movies/21
Accept: application/json
Content-Type: application/json

{
  "id": 21,
  "title": "-------",
  "trailer": "-----",
  "year": 0,
  "rating": 0,
  "description": "0 из 10!",
  "genre_id": 1,
  "director_id": 1
}

###

PATCH http://127.0.0.1:10001/movies/3
Accept: application/json
Content-Type: application/json

{
  "id": 21,
  "title": "-------",
  "trailer": "-----",
  "year": 0,
  "rating": 0,
  "description": "0 из 10!",
  "genre_id": 1,
  "director_id": 1
}

###

DELETE http://127.0.0.1:10001/movies/21

###

POST http://127.0.0.1:10001/auth/register/
Accept: application/json
Content-Type: application/json

{
  "email": "test-register4@mail.ru",
  "password": "qwerty1"
}

###

POST http://127.0.0.1:10001/auth/login/
Accept: application/json
Content-Type: application/json

{
  "email": "test-register3@mail.ru",
  "password": "qwerty1"
}

###

PUT http://127.0.0.1:10001/auth/login/
Accept: application/json
Content-Type: application/json

{
  "refresh_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3QtcmVnaXN0ZXIzQG1haWwucnUiLCJleHAiOjE2NjU2NjY5OTl9.LguaZsiWqq6Q8PMV7IBY2gkYJ0zRrsHW0VfBcQuivJA"
}

###

GET http://127.0.0.1:10001/users/1
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3QtcmVnaXN0ZXIzQG1haWwucnUiLCJleHAiOjE2NTQ0Mzc4Nzl9.TrZ8jnhRH94ubC7x0GihVx007ae2AiiI7-ylRtSN_sE


###

PATCH http://127.0.0.1:10001/users/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3QtcmVnaXN0ZXIzQG1haWwucnUiLCJleHAiOjE2NTQ0Mzc4Nzl9.TrZ8jnhRH94ubC7x0GihVx007ae2AiiI7-ylRtSN_sE

{
  "name": "TEST PATCH",
  "favorite_genre": "first",
  "surname": "first"
}
###

PUT http://127.0.0.1:10001/users/2/password
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRlc3QtcmVnaXN0ZXIzQG1haWwucnUiLCJleHAiOjE2NTQ0Mzc4Nzl9.TrZ8jnhRH94ubC7x0GihVx007ae2AiiI7-ylRtSN_sE

{
  "password_1": "qwerty1",
  "password_2": "qwerty2PUT"
}
###